name: NodeJS Version

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/**"
      - "src/**"
      - "tests/**"
      - '.releaserc.helm.json'
      - '.releaserc.json'
      - 'astro.config.mjs'
      - 'biome.json'
      - 'commitlint.config.cjs'
      - 'lefthook.yml'
      - 'snodeb.config.cjs'
      - 'tsup.config.cjs'
      - 'vitest.config.cjs'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - ".github/**"
      - "src/**"
      - "tests/**"
      - '.releaserc.helm.json'
      - '.releaserc.json'
      - 'astro.config.mjs'
      - 'biome.json'
      - 'commitlint.config.cjs'
      - 'lefthook.yml'
      - 'snodeb.config.cjs'
      - 'tsup.config.cjs'
      - 'typedoc.json'
      - 'vitest.config.cjs'
      - 'package.json'
      - 'package-lock.json'

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    with:
      node_version: '22'
      working_directory: '.'
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write

  library:
    uses: ./.github/workflows/library.yml
    needs: [testing]
    with:
      enable_secrets: false
      node_version: '22'
      working_directory: '.'
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
