name: ForgeJS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  index:
    uses: ./.github/workflows/library.yml
    with:
      node_version: '22'
      working_directory: '.'
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write

  pages:
    uses: ./.github/workflows/.pages.yml
    with:
      node_version: '22'
      working_directory: 'docs'
      enable_secrets: false
    permissions:
      contents: write
      id-token: write
      pages: write
      pull-requests: write
