name: ForgeJS CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    uses: ./.github/workflows/testing.yml
    with:
      node_version: '22'
      working_directory: '.'
    permissions:
      contents: read
      pull-requests: write

  library:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/library.yml
    needs: [testing]
    with:
      enable_secrets: false
      node_version: '22'
      working_directory: '.'
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write

  document:
    uses: ./.github/workflows/document.yml
    with:
      node_version: '22'
      working_directory: 'docs'
      enable_secrets: false
    permissions:
      contents: write
      id-token: write
      pages: write

