name: ForgeJS Pages

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: 'docs'
      enable_secrets:
        required: false
        type: boolean
        default: true
      auto_patch:
        required: false
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/testing.yml
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_secrets: ${{ inputs.enable_secrets }}
      run_tests: false
      artifact_name: 'pages-dist'
      auto_patch: ${{ inputs.auto_patch }}

  deploy:
    uses: ./.github/workflows/website.yml
    needs: [build]
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_versioning: false
      artifact_name: 'pages-dist'
