name: ForgeJS Pages

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: 'docs'
      enable_secrets:
        required: false
        type: boolean
        default: true

jobs:
  quality:
    uses: ./.github/workflows/quality.yml
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_secrets: ${{ inputs.enable_secrets }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [quality]
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v7
        with:
          name: pages-dist
          path: ${{ inputs.working_directory }}/dist

  deploy:
    uses: ./.github/workflows/website.yml
    needs: [build]
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_versioning: false
      artifact_name: 'pages-dist'
