name: NodeJS Build

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: 'dist'
      enable_secrets:
        required: false
        type: boolean
        default: true
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: '.'

jobs:
  setup:
    uses: ./.github/workflows/default.yml
    with:
      enable_secrets: ${{ inputs.enable_secrets }}
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [setup]
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.working_directory }}/dist
