name: NodeJS Debian

on:
  workflow_call:
    inputs:
      enable_secrets:
        required: false
        type: boolean
        default: true
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: '.'
      auto_patch:
        required: false
        type: boolean
        default: false
      build_env_vars:
        required: false
        type: string
        default: ''

jobs:
  auto-merge:
    uses: ./.github/workflows/merge.yml
    permissions:
      contents: write
      pull-requests: write

  testing:
    uses: ./.github/workflows/testing.yml
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_secrets: ${{ inputs.enable_secrets }}
      auto_patch: ${{ inputs.auto_patch }}
      build_env_vars: ${{ inputs.build_env_vars }}

  version:
    uses: ./.github/workflows/version.yml
    needs: [testing]
    with:
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [version]
    if: github.ref == 'refs/heads/main' && (needs.version.outputs.new_release_published == 'true' || needs.version.outputs.new_release_published == true)
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v7
        with:
          name: dist
          path: ${{ inputs.working_directory }}/dist
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Debian Package
        run: |
          if [ -f .env.production ]; then
            cp .env.production .env
          else
            echo "No .env.production found"
          fi

          npx snodeb

          mkdir -p deb_output
          mv ./deb/*.deb ./deb_output/
      - name: Upload Debian Artifact
        uses: actions/upload-artifact@v7
        with:
          name: debian-package
          path: ${{ inputs.working_directory }}/deb_output/*.deb
