name: NodeJS Document

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: 'docs'
      enable_secrets:
        required: false
        type: boolean
        default: true

jobs:
  quality:
    uses: ./.github/workflows/quality.yml
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_secrets: ${{ inputs.enable_secrets }}
      artifact_name: 'dist'

  website:
    uses: ./.github/workflows/website.yml
    needs: [quality]
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_secrets: ${{ inputs.enable_secrets }}
      enable_versioning: false
