name: NodeJS Library

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: 'dist'
      enable_secrets:
        required: false
        type: boolean
        default: true
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: '.'
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      enable_secrets: ${{ inputs.enable_secrets }}
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}

  document:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [version]
    if: github.ref == 'refs/heads/main' && needs.version.outputs.new_release_published == 'true'
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Documentation
        run: npm run doc
      - name: Prepare Pages
        run: |
          mkdir -p public/assets
          cp -r ./docs/. ./public/
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ inputs.working_directory }}/public

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [version, document]
    if: github.ref == 'refs/heads/main' && needs.version.outputs.new_release_published == 'true'
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.working_directory }}/dist
      - uses: actions/download-artifact@v6
        with:
          name: updated-package-json
          path: ${{ inputs.working_directory }}
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
