name: NodeJS Service

on:
  workflow_call:
    inputs:
      enable_secrets:
        required: false
        type: boolean
        default: true
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: '.'
      auto_patch:
        required: false
        type: boolean
        default: true
      build_env_vars:
        required: false
        type: string
        default: ''

jobs:
  auto-merge:
    uses: ./.github/workflows/merge.yml
    permissions:
      contents: write
      pull-requests: write

  testing:
    uses: ./.github/workflows/testing.yml
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      enable_secrets: ${{ inputs.enable_secrets }}
      auto_patch: ${{ inputs.auto_patch }}
      build_env_vars: ${{ inputs.build_env_vars }}

  version:
    uses: ./.github/workflows/version.yml
    needs: [testing]
    with:
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}
