name: NodeJS Tests

on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        type: string
        default: '.'
      node_version:
        required: false
        type: string
        default: '22'
      auto_patch:
        required: false
        type: boolean
        default: false
      enable_secrets:
        required: false
        type: boolean
        default: true

jobs:
  quality:
    uses: ./.github/workflows/quality.yml
    with:
      working_directory: ${{ inputs.working_directory }}
      node_version: ${{ inputs.node_version }}
      auto_patch: ${{ inputs.auto_patch }}
      enable_secrets: ${{ inputs.enable_secrets }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [quality]
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@${{ github.repository_owner }}"
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tests
        run: npm test
      - name: Upload Coverage
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: ${{ inputs.working_directory }}/coverage
          if-no-files-found: ignore
