name: NodeJS Version

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: 'dist'
      enable_secrets:
        required: false
        type: boolean
        default: true
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: '.'
    outputs:
      new_release_published:
        description: "Whether a new release was published"
        value: ${{ jobs.release-please.outputs.release_created }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

  build:
    needs: [release-please]
    if: needs.release-please.outputs.release_created
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: ${{ inputs.artifact_name }}
      enable_secrets: ${{ inputs.enable_secrets }}
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}
