name: GitHub Pages Deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: 'dist'
      enable_secrets:
        required: false
        type: boolean
        default: true
      node_version:
        required: false
        type: string
        default: '22'
      working_directory:
        required: false
        type: string
        default: '.'
      enable_versioning:
        required: false
        type: boolean
        default: true

jobs:
  version:
    if: inputs.enable_versioning
    uses: ./.github/workflows/version.yml
    with:
      enable_secrets: ${{ inputs.enable_secrets }}
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.working_directory }}

  deploy:
    runs-on: ubuntu-latest
    needs: [version]
    if: github.ref == 'refs/heads/main' && (!inputs.enable_versioning || needs.version.outputs.new_release_published == 'true' || needs.version.outputs.new_release_published == true)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact_name }}
          path: ./pages-artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages-artifact
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
